# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "heartrates", :force => true do |t|
    t.column "user_id",   :integer
    t.column "timestamp", :datetime
    t.column "heartrate", :integer,  :null => false
  end

  create_table "raw_data_files", :force => true do |t|
    t.column "filename",     :string
    t.column "content_type", :string
    t.column "size",         :integer
    t.column "parent_id",    :integer
    t.column "created_at",   :datetime
  end

end
